### ISSUE TITLE
Failed to build LineageOS 20

### ISSUE THREAD

**Issue by TYOPXN360** [xiaomi-mt6893-dev/android_device_xiaomi_chopin#1]
Offending entries:
android.hardware.usb-service.mediatek
build/make/core/main.mk:1312: error: Build failed

  
  <project name="xiaomi-mt6893-dev/android_device_xiaomi_chopin" path="device/xiaomi/chopin" remote="github" revision="dev/lineage-20" />
  
  <project name="xiaomi-mt6893-dev/android_kernel_xiaomi_chopin-prebuilt" path="device/xiaomi/chopin-kernel" remote="github" revision="main" />
  
  <project name="xiaomi-mt6893-dev/android_vendor_xiaomi_chopin" path="vendor/xiaomi/chopin" remote="github" revision="13-old" />
  
  <project name="LineageOS/android_device_mediatek_sepolicy_vndr" path="device/mediatek/sepolicy_vndr" remote="github" revision="lineage-20" />
  
  <project name="LineageOS/android_hardware_xiaomi" path="hardware/xiaomi" remote="github" revision="lineage-20" />
  
  <project name="LineageOS/android_hardware_mediatek" path="hardware/mediatek" remote="github" revision="lineage-20" />

Did I use it incorrectly somewhere?

**Comment by AbzRaider** [comment]
@TYOPXN360 omfg

**Comment by AbzRaider** [comment]
well the tree is not stable yet and u need to clone hardware/mediatek from my repository to build and hardware/xiaomi from lineageos git

**Comment by TYOPXN360** [comment]
> 嗯，树还不稳定，您需要从我的存储库克隆 hardware/Mediatek 来构建，并从 Lineageos git 克隆 hardware/xiaomi

**Comment by TYOPXN360** [comment]
> well the tree is not stable yet and u need to clone hardware/mediatek from my repository to build and hardware/xiaomi from lineage

Ok, I'll try. By the way, Is the los21 tree available for construction now?

**Comment by AbzRaider** [comment]
> > well the tree is not stable yet and u need to clone hardware/mediatek from my repository to build and hardware/xiaomi from lineage
> 
> Ok, I'll try. By the way, Is the los21 tree available for construction now?

the los21 tree is not bootable only lineage-20 works RIL is dead wifi/bt is dead c2 hal crashes

**Comment by TYOPXN360** [comment]
> the los21 tree is not bootable only lineage-20 works RIL is dead wifi/bt is dead c2 hal crashes

Is there a known bug in los20?

**Comment by AbzRaider** [comment]
@TYOPXN360 in lineage 20 RIL ( SIM ) doesn't work camera support not added nfc not added fingerprint not added c2 hal doesn't work properly ( video crashes )
device random reboots , wifi and bluetooth doesn't work

**Comment by TYOPXN360** [comment]
> @TYOPXN360 in lineage 20 RIL ( SIM ) doesn't work camera support not added nfc not added fingerprint not added c2 hal doesn't work properly ( video crashes )
> device random reboots , wifi and bluetooth doesn't work

How long will it take to get a stable tree?

**Comment by AbzRaider** [comment]
> > @TYOPXN360 in lineage 20 RIL ( SIM ) doesn't work camera support not added nfc not added fingerprint not added c2 hal doesn't work properly ( video crashes )
> > device random reboots , wifi and bluetooth doesn't work
> 
> How long will it take to get a stable tree?

i have less time to work but for now many issues have been fixed wifi bt works

**Comment by TYOPXN360** [comment]
> i have less time to work but for now many issues have been fixed wifi bt works

Merry Christmas. I'm glad to hear the good news, but the compilation is still wrong. I have replaced hardware/mediatek.

device/xiaomi/chopin/libinit/init_xiaomi_chopin.cpp:24:5: error: use of undeclared identifier 'amber_info'
    amber_info,
    ^
1 error generated.
19:46:56 ninja failed with: exit status 1

#### failed to build some targets (-nan:-nan (mm:ss)) ####

**Comment by AbzRaider** [comment]
@TYOPXN360 use test4 branch

**Comment by AbzRaider** [comment]
@AbzRaider and well i havent synced the latest kernel its private i dont think u can boot

**Comment by TYOPXN360** [comment]
> @AbzRaider and well i havent synced the latest kernel its private i dont think u can boot

**Comment by TYOPXN360** [comment]
> @AbzRaider and well i havent synced the latest kernel its private i dont think u can boot

Can you send me an anykernel zip that can flash? I want to try to boot a system builded using this device tree.

**Comment by TYOPXN360** [comment]
hey, it turns on, but the touch doesn't work, and neither does the audio

**Comment by AbzRaider** [comment]
@TYOPXN360 Sorry I can't share the OSS Kernel for now as its under development if you want to test stuff join testing group you can dm me on telegram
